### ISSUE TITLE
Descriptions and images lost from web view

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6348]
- Added by [Paul Cannon](http://fungi.myspecies.info/user/2)
- Scratchpad: [Fungi of Great Britain and Ireland](http://fungi.myspecies.info)

### Description:

Help! The descriptions, images, biblio tags etc. have all disappeared from the species pages on http:/fungi.myspecies.info, and clicking on the recently added taxon descriptions on the front page gives an "Access denied" message. 
Maybe something to do with http://fungi.myspecies.info/issues/6313?

A quick fix would be greatly appreciated!
Paul

**Comment by PaulKiddle** [comment]
Hi Paul, I believe this should be fixed now - can you check everything is ok?

Caused by the same bug as #6349

**Comment by scratchpads** [comment]
Comment by [Paul Cannon](http://fungi.myspecies.info/user/2)

No, still getting access denied by clicking on the taxon descriptions on the front page, and images are not showing on the "home" page for individual species (e.g. http://fungi.myspecies.info/all-fungi/candelaria-concolor) - I think there's a tab still missing.
Thanks for working on this
Paul

**Comment by scratchpads** [comment]
Comment by [Paul Cannon](http://fungi.myspecies.info/user/2)

Hope progress is being made! Additionally, I've been getting a lot of time-outs over the past few days - is there a more general traffic problem?

Best wishes
Paul

**Comment by PaulKiddle** [comment]
There is, I'm investigating currently.

**Comment by Archilegt** [comment]
A partial explanation for the time-outs may be the increase in Scratchpads
security. When I was unable to reach my site, I also got time-outs. Adding
Paul Cannon's IP to the trusted IPs may solve that issue.

**Comment by PaulKiddle** [comment]
I think the access denied issue is related to the tabs configuration work from a while ago, since only the '{tid}/descriptions' url seems to be affected. I will be able to dig deeper after the weekend.

**Comment by scratchpads** [comment]
Comment by [Paul Cannon](http://fungi.myspecies.info/user/2)

Any chance of a further progress report? I'm getting a fair few complaints from users now, and almost all the tabs have now disappeared from the species pages...

Best wishes
Paul

**Comment by PaulKiddle** [comment]
Looks like the tabs had been disabled on the taxonomy settings form http://fungi.myspecies.info/structure/taxonomy/all_fungi/edit
I've re-enabled them and they're now showing again. I'm also not seeing the Access Denied message any longer, so considering this issue resolved.
